### ISSUE TITLE
using on a vanilla HA install

### ISSUE THREAD

**Issue by IanAdd** [MrPasty/network-monitor#1]
Any clues on how to get this to work on an install of HA on a pi4 on hassio.
I've got your python code and when I try to run it it complains it can't find 'nmap' to import. I use nmap_tracker integration which I assume is related.

**Comment by MrPasty** [comment]
That would suggest that you do not have python3-nmap installed?

**Comment by IanAdd** [comment]
This proved to be the easier start to a solution
```
{% for dev in states.device_tracker | list  %}
 entity_id: {{ dev.entity_id }}
 friendly name: {{ dev.name }}
 source_type: {{ dev.source_type }}
 state: {{dev.state}}
 last changed: {{ dev.last_changed }}
{% endfor %}
```
